version: 'Compose specification'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
    ports:
      - 3306:3306
    volumes:
      - /home/dbdata:/var/lib/mysql
  app:
    build: .
    ports:
      - 8080:8080
