version: 'Compose specification'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
    ports:
      - 3306:3306
    # volumes:
    #   - /home/dbdata:/var/lib/mysql
