services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
    ports:
      - 3306:3306
    volumes:
      - /home/inciner8r/DragonLore/projeccs/dbdata:/var/lib/mysql
